let groupData = [
  {
    name:'自然类',
    title:'nature',
    icon:'explore'
  },
  {
    name:'建筑类',
    title:'architecture',
    icon:'house'
  },
  {
    name:'鬼神类',
    title:'hobgoblin',
    icon:'eye'
  },
  {
    name:'植物类',
    title:'botany',
    icon:'more'
  },
  {
    name:'动物类',
    title:'animal',
    icon:'ios'
  },
  {
    name:'身体类',
    title:'body',
    icon:'people'
  },
  {
    name:'物品类',
    title:'goods',
    icon:'bag'
  },  
  {
    name:'情爱类',
    title:'love',
    icon:'like'
  },
  {
    name:'生活类',
    title:'life',
    icon:'home'
  },
  {
    name:'人物类',
    title:'figure',
    icon:'friendadd'
  }
];
let mobilePage = [
  {
    title:'保险客服',
    isShow:false,
    list:[
      {title:'阳光保险',mobile:'95510'},
      {title:'平安保险',mobile:'95512'},
      {title:'中华保险',mobile:'95585'},
      {title:'大地保险',mobile:'95590'},
      {title:'太平保险',mobile:'95589'},
      {title:'太平洋保险',mobile:'95500'},
      {title:'民生人寿保险',mobile:'95596'},
      {title:'中国人民保险',mobile:'95518'},
      {title:'生命人寿保险',mobile:'95535'},
      {title:'合众人寿保险',mobile:'95515'},
      {title:'中国人寿保险',mobile:'95519'},
      {title:'新华人寿保险',mobile:'95567'},
      {title:'康泰人寿保险',mobile:'95522'}
    ]
  },
  {
    title:'旅行预订电话',
    isShow:false,
    list:[
      {title:'携程网',mobile:'4008206666'},
      {title:'同程网',mobile:'4007777777'},
      {title:'途牛网',mobile:'4007999999'},
      {title:'艺龙网',mobile:'4009333333'},
      {title:'芒果网',mobile:'4006640066'},
      {title:'去哪儿网',mobile:'10101234'},
    ]
  },
  {
    title:'快递公司客服电话',
    isShow:false,
    list:[
      {title:'申通快递',mobile:'95543'},
      {title:'韵达快递',mobile:'95546'},
      {title:'中通快递',mobile:'95311'},
      {title:'百世汇通',mobile:'4009565656'},
      {title:'顺丰速运',mobile:'95338'},
      {title:'圆通快递',mobile:'95554'},
      {title:'德邦物流',mobile:'95353'},
      {title:'邮政快递专递',mobile:'11185'}
    ]
  },  
  {
    title:'公共服务、常用、紧急电话',
    isShow:false,
    list:[
      {title:'火警电话',mobile:'119'},
      {title:'报警电话',mobile:'110'},
      {title:'急救电话',mobile:'120'},
      {title:'号码查询电话',mobile:'114'},
      {title:'紧急呼叫中心',mobile:'112'},
      {title:'报时服务电话',mobile:'12117'},
      {title:'气象服务电话',mobile:'12121'},
      {title:'红十字会急救台',mobile:'999'},
      {title:'道路交通事故报警',mobile:'122'},
      {title:'水上遇险求救电话',mobile:'12395'},
      {title:'公安短信报警号码',mobile:'12110'},
      {title:'全国铁路客服中心',mobile:'12306'},
      {title:'邮政客服服务电话',mobile:'11185'},
      {title:'全国法律服务电话',mobile:'12348'},
    ]
  },
  {
    title:'全国通信机构服务电话号码',
    isShow:false,
    list:[
      {title:'铁通客户服务',mobile:'10050'},
      {title:'中国移动IP号码',mobile:'17951'},
      {title:'中国联通IP号码',mobile:'17911'},
      {title:'中国联通客服热线',mobile:'10010'},
      {title:'中国电信IP电话卡',mobile:'17900'},
      {title:'中国移动客服热线',mobile:'10086'},
      {title:'中国电信号码百事通',mobile:'118114'},
      {title:'中国电信客户服务热线',mobile:'10000'},
      {title:'中国垃圾短信投诉号码',mobile:'10086999'},
      {title:'中国联通的“电话导航”业务',mobile:'116114'}
    ]
  },
  {
    title:'全国银行客户服务电话号码',
    isShow:false,
    list:[
      {title:'招商银行',mobile:'95555'},
      {title:'中国银行',mobile:'95555'},
      {title:'建设银行',mobile:'95555'},
      {title:'工商银行',mobile:'95555'},
      {title:'中信银行',mobile:'95555'},
      {title:'浦发银行',mobile:'95555'},
      {title:'深发银行',mobile:'95555'},
      {title:'农业银行',mobile:'95555'},
      {title:'民生银行',mobile:'95555'},
      {title:'光大银行',mobile:'95555'},
      {title:'交通银行',mobile:'95555'},
      {title:'广发银行',mobile:'95555'},
      {title:'华夏银行',mobile:'95555'},
      {title:'兴业银行',mobile:'95555'},
    ]
  },  
  {
    title:'监督、投诉、抢修、举报电话',
    isShow:false,
    list:[
      {title:'质量监督电话',mobile:'12365'},
      {title:'环保局监督电话',mobile:'12369'},
      {title:'民工维权热线电话',mobile:'12333'},
      {title:'公共卫生环境投诉',mobile:'12320'},
      {title:'电力系统客服电话',mobile:'95598'},
      {title:'价格监督举报电话',mobile:'12358'},
      {title:'政府公益服务接入网',mobile:'12345'},
      {title:'文化市场统一举报电话',mobile:'12318'},
      {title:'机构编制违规举报热线',mobile:'12310'},
      {title:'消费者投诉举报专线电话',mobile:'12315'}
    ]
  }
]
module.exports = {
  groupData,
  mobilePage
};